<a href="https://colab.research.google.com/github/RIYAENGINEER/Car-Sales/blob/main/carsales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/Car_sales.csv")
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [ ]:
df["Latest_Launch"]=pd.to_datetime(df["Latest_Launch"],format="%m/%d/%Y")

In [ ]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,0,79,16.919,16.360,1,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,47,58.280150
1,0,143,39.384,19.875,1,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,93,91.370778
2,0,25,14.114,18.225,1,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,9,NaN
3,0,115,8.588,29.725,1,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,52,91.389779
4,1,8,20.397,22.255,1,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,20,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,29,148,3.545,NaN,1,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,124,66.498812
153,29,125,15.245,NaN,1,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,26,70.654495
154,29,149,17.531,NaN,1,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,89,71.155978
155,29,24,3.493,NaN,1,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,71,101.623357
156,29,126,18.969,NaN,1,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,22,85.735655

In [ ]:
print(df.isnull().sum())

Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    36
Vehicle_type            0
Price_in_thousands      2
Engine_size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb_weight             2
Fuel_capacity           1
Fuel_efficiency         3
Latest_Launch           0
Power_perf_factor       2
dtype: int64

In [ ]:
df_clean = df.dropna(subset=['__year_resale_value'])

In [ ]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,0,79,16.919,16.360,1,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,47,58.280150
1,0,143,39.384,19.875,1,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,93,91.370778
2,0,25,14.114,18.225,1,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,9,NaN
3,0,115,8.588,29.725,1,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,52,91.389779
4,1,8,20.397,22.255,1,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,20,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,29,148,3.545,NaN,1,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,124,66.498812
153,29,125,15.245,NaN,1,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,26,70.654495
154,29,149,17.531,NaN,1,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,89,71.155978
155,29,24,3.493,NaN,1,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,71,101.623357
156,29,126,18.969,NaN,1,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,22,85.735655

In [ ]:
print(df.isnull().sum())

Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    36
Vehicle_type            0
Price_in_thousands      2
Engine_size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb_weight             2
Fuel_capacity           1
Fuel_efficiency         3
Latest_Launch           0
Power_perf_factor       2
dtype: int64

In [ ]:
df['__year_resale_value'] = df['__year_resale_value'].fillna(0)  # or 'unknown', 999, etc.

In [ ]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2012-02-02,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,2011-06-03,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,2012-01-04,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2011-03-10,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,2011-10-08,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,0.000,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,2011-09-21,66.498812
153,Volvo,S70,15.245,0.000,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,2012-11-24,70.654495
154,Volvo,V70,17.531,0.000,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,2011-06-25,71.155978
155,Volvo,C70,3.493,0.000,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,2011-04-26,101.623357
156,Volvo,S80,18.969,0.000,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,2011-11-14,85.735655

In [ ]:
df = df.dropna(subset=['Price_in_thousands'])

In [ ]:
print(df.isnull().sum())

Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    36
Vehicle_type            0
Price_in_thousands      0
Engine_size             0
Horsepower              0
Wheelbase               0
Width                   0
Length                  0
Curb_weight             1
Fuel_capacity           0
Fuel_efficiency         2
Latest_Launch           0
Power_perf_factor       0
dtype: int64

In [ ]:
df = df.dropna(subset=['Price_in_thousands','Fuel_efficiency','Curb_weight'])

In [ ]:
print(df.isnull().sum())

Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    35
Vehicle_type            0
Price_in_thousands      0
Engine_size             0
Horsepower              0
Wheelbase               0
Width                   0
Length                  0
Curb_weight             0
Fuel_capacity           0
Fuel_efficiency         0
Latest_Launch           0
Power_perf_factor       0
dtype: int64

In [ ]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2012-02-02,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,2011-06-03,91.370778
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2011-03-10,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,2011-10-08,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2011-08-09,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,2011-09-21,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,2012-11-24,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,2011-06-25,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,2011-04-26,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,2011-11-14,85.735655

In [ ]:
for j in df.select_dtypes(include="object").columns:
  print(j,df[j].unique())

Manufacturer ['Acura' 'Audi' 'BMW' 'Buick' 'Cadillac' 'Chevrolet' 'Chrysler' 'Dodge'
 'Ford' 'Honda' 'Hyundai' 'Infiniti' 'Jaguar' 'Jeep' 'Lexus' 'Lincoln'
 'Mitsubishi' 'Mercury' 'Mercedes-B' 'Nissan' 'Oldsmobile' 'Plymouth'
 'Pontiac' 'Porsche' 'Saab' 'Saturn' 'Subaru' 'Toyota' 'Volkswagen'
 'Volvo']
Model ['Integra' 'TL' 'RL' 'A4' 'A6' 'A8' '323i' '328i' '528i' 'Century' 'Regal'
 'Park Avenue' 'LeSabre' 'DeVille' 'Eldorado' 'Catera' 'Escalade'
 'Cavalier' 'Malibu' 'Lumina' 'Monte Carlo' 'Camaro' 'Corvette' 'Prizm'
 'Metro' 'Impala' 'Sebring Coupe' 'Sebring Conv.' 'Concorde' 'Cirrus'
 'LHS' '300M' 'Neon' 'Avenger' 'Stratus' 'Viper' 'Ram Pickup' 'Ram Wagon'
 'Ram Van' 'Dakota' 'Durango' 'Caravan' 'Escort' 'Mustang' 'Contour'
 'Taurus' 'Focus' 'Crown Victoria' 'Explorer' 'Windstar' 'Expedition'
 'Ranger' 'F-Series' 'Civic' 'Accord' 'CR-V' 'Passport' 'Odyssey' 'Accent'
 'Elantra' 'Sonata' 'I30' 'S-Type' 'Wrangler' 'Cherokee' 'Grand Cherokee'
 'ES300' 'GS300' 'GS400' 'LS400' 'LX470' 'RX300' 'Continental' 'Town car'
 'Navigator' 'Mirage' 'Eclipse' 'Galant' 'Diamante' '3000GT' 'Montero'
 'Montero Sport' 'Mystique' 'Cougar' 'Sable' 'Grand Marquis' 'Mountaineer'
 'Villager' 'C-Class' 'E-Class' 'S-Class' 'SL-Class' 'SLK' 'SLK230'
 'CLK Coupe' 'CL500' 'M-Class' 'Sentra' 'Altima' 'Maxima' 'Quest'
 'Pathfinder' 'Xterra' 'Frontier' 'Cutlass' 'Alero' 'Aurora' 'Bravada'
 'Silhouette' 'Breeze' 'Voyager' 'Prowler' 'Sunfire' 'Grand Am' 'Firebird'
 'Grand Prix' 'Bonneville' 'Montana' 'Boxter' 'Carrera Coupe'
 'Carrera Cabrio' '5-Sep' '3-Sep' 'SL' 'SC' 'SW' 'LW' 'LS' 'Outback'
 'Forester' 'Corolla' 'Camry' 'Avalon' 'Celica' 'Tacoma' 'Sienna' 'RAV4'
 '4Runner' 'Land Cruiser' 'Golf' 'Jetta' 'Passat' 'Cabrio' 'GTI' 'Beetle'
 'S40' 'V40' 'S70' 'V70' 'C70' 'S80']
Vehicle_type ['Passenger' 'Car']

In [ ]:
from sklearn.preprocessing import LabelEncoder #scikit learn
df_LableEncoder=LabelEncoder()

In [ ]:
for j in df.select_dtypes(include="object").columns:
  df[j]=df_LableEncoder.fit_transform(df[j])

In [ ]:
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,0,78,16.919,16.360,1,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2012-02-02,58.280150
1,0,139,39.384,19.875,1,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,2011-06-03,91.370778
3,0,112,8.588,29.725,1,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,2011-03-10,91.389779
4,1,8,20.397,22.255,1,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,2011-10-08,62.777639
5,1,9,18.780,23.555,1,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,2011-08-09,84.565105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,29,143,3.545,NaN,1,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,2011-09-21,66.498812
153,29,122,15.245,NaN,1,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,2012-11-24,70.654495
154,29,144,17.531,NaN,1,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,2011-06-25,71.155978
155,29,24,3.493,NaN,1,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,2011-04-26,101.623357
156,29,123,18.969,NaN,1,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,2011-11-14,85.735655

In [ ]:
df.corr()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
Manufacturer,1.000000,0.089773,-0.166702,0.006618,-0.019287,-0.045367,-0.270818,-0.200931,-0.287816,-0.299179,-0.306711,-0.179964,-0.161189,0.108868,-0.115799,-0.173335
Model,0.089773,1.000000,-0.014742,-0.132309,-0.226068,-0.068969,0.054455,-0.041360,0.085473,0.099746,0.021307,0.082624,0.089842,-0.081147,-0.043371,-0.047654
Sales_in_thousands,-0.166702,-0.014742,1.000000,-0.275426,-0.243023,-0.301850,0.027716,-0.192519,0.360186,0.143664,0.260162,0.008784,0.087437,-0.016474,0.099311,-0.220031
__year_resale_value,0.006618,-0.132309,-0.275426,1.000000,0.091679,0.954757,0.527187,0.773110,-0.053685,0.178128,0.025390,0.363274,0.324796,-0.398459,-0.066848,0.829511
Vehicle_type,-0.019287,-0.226068,-0.243023,0.091679,1.000000,0.042077,-0.268810,-0.016786,-0.396693,-0.260225,-0.149919,-0.526428,-0.599317,0.576931,0.023348,-0.007023
Price_in_thousands,-0.045367,-0.068969,-0.301850,0.954757,0.042077,1.000000,0.623545,0.841062,0.108494,0.328493,0.154924,0.527148,0.423980,-0.491391,-0.016357,0.898948
Engine_size,-0.270818,0.054455,0.027716,0.527187,-0.268810,0.623545,1.000000,0.836649,0.472586,0.692124,0.542036,0.760908,0.666948,-0.737267,0.082801,0.816362
Horsepower,-0.200931,-0.041360,-0.192519,0.773110,-0.016786,0.841062,0.836649,1.000000,0.282166,0.534726,0.384787,0.610549,0.505455,-0.616075,0.072925,0.993012
Wheelbase,-0.287816,0.085473,0.360186,-0.053685,-0.396693,0.108494,0.472586,0.282166,1.000000,0.681205,0.840137,0.651443,0.656815,-0.497305,0.086270,0.254308
Width,-0.299179,0.099746,0.143664,0.178128,-0.260225,0.328493,0.692124,0.534726,0.681205,1.000000,0.705746,0.723284,0.663125,-0.602309,0.124915,0.506867
Length,-0.306711,0.021307,0.260162,0.025390,-0.149919,0.154924,0.542036,0.384787,0.840137,0.705746,1.000000,0.629261,0.570932,-0.447442,0.110384,0.347225
Curb_weight,-0.179964,0.082624,0.008784,0.363274,-0.526428,0.527148,0.760908,0.610549,0.651443,0.723284,0.629261,1.000000,0.864891,-0.819622,0.032942,0.612011
Fuel_capacity,-0.161189,0.089842,0.087437,0.324796,-0.599317,0.423980,0.666948,0.505455,0.656815,0.663125,0.570932,0.864891,1.000000,-0.801783,0.100032,0.504323
Fuel_efficiency,0.108868,-0.081147,-0.016474,-0.398459,0.576931,-0.491391,-0.737267,-0.616075,-0.497305,-0.602309,-0.447442,-0.819622,-0.801783,1.000000,-0.053757,-0.608267
Latest_Launch,-0.115799,-0.043371,0.099311,-0.066848,0.023348,-0.016357,0.082801,0.072925,0.086270,0.124915,0.110384,0.032942,0.100032,-0.053757,1.000000,0.055491
Power_perf_factor,-0.173335,-0.047654,-0.220031,0.829511,-0.007023,0.898948,0.816362,0.993012,0.254308,0.506867,0.347225,0.612011,0.504323,-0.608267,0.055491,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 152 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         152 non-null    int64
 1   Model                152 non-null    int64
 2   Sales_in_thousands   152 non-null    float64
 3   __year_resale_value  117 non-null    float64
 4   Vehicle_type         152 non-null    int64
 5   Price_in_thousands   152 non-null    float64
 6   Engine_size          152 non-null    float64
 7   Horsepower           152 non-null    float64
 8   Wheelbase            152 non-null    float64
 9   Width                152 non-null    float64
 10  Length               152 non-null    float64
 11  Curb_weight          152 non-null    float64
 12  Fuel_capacity        152 non-null    float64
 13  Fuel_efficiency      152 non-null    float64
 14  Latest_Launch        152 non-null    datetime64[ns]
 15  Power_perf_factor    152 non-null    float64
dtypes: datetime64[ns](1), float64(12), int64(3)
memory usage: 20.2 KB